quarkus.http.port=8091
quarkus.http.host=0.0.0.0
quarkus.native.additional-build-args=--initialize-at-run-time=com.scivicslab.turingworkflow.workflow.Interpreter
workflow.params.base-dir=/home/devteam/works/workflow/environment-parameters
workflow.dir=/home/devteam/works/workflow
